server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: produtos-service
            uri: lb://PRODUTOS
            predicates:
              - Path=/api-produtos/**
          - id: notificacao-service
            uri: lb://NOTIFICACAO
            predicates:
              - Path=/api-notificacao/**


eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost

