INSERT INTO TB_PRODUTO (NOME, PRECO, DATA_INCLUSAO) VALUES ('Pera', 2.40, NOW());
INSERT INTO TB_PRODUTO (NOME, PRECO, DATA_INCLUSAO) VALUES ('Mexerica', 5.40, NOW());

INSERT INTO TB_HISTORICO_PRODUTO(NOME, PRECO, ID_PRODUTO, DATA_INCLUSAO) VALUES ('Maça', 2.40, 1, NOW());
INSERT INTO TB_HISTORICO_PRODUTO(NOME, PRECO, ID_PRODUTO, DATA_INCLUSAO) VALUES ('Mexerica', 5.40, 2, NOW());

INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Administrador', 'ROLE_ADMIN');
INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Funcionário', 'ROLE_FUNCIONARIO');
INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Cliente', 'ROLE_CLIENTE');

INSERT INTO TB_USUARIO (NOME, EMAIL, SENHA, DATA_INCLUSAO) VALUES ('Teste 123', 'teste123@email.com.br', '@Aa123', NOW());
INSERT INTO TB_USUARIO_PERFIL (ID_USUARIO, ID_PERFIL) VALUES (1, 1);

INSERT INTO TB_PEDIDO (DATA, PEDIDO_STATUS, ID_USUARIO, DATA_INCLUSAO) VALUES (NOW(), 'ABERTO', 1, NOW());
INSERT INTO TB_PEDIDO (DATA, PEDIDO_STATUS, ID_USUARIO, DATA_INCLUSAO) VALUES (NOW(), 'FINALIZADO', 1, NOW());
INSERT INTO TB_PEDIDO (DATA, PEDIDO_STATUS, ID_USUARIO, DATA_INCLUSAO) VALUES (NOW(), 'CANCELADO', 1, NOW());

INSERT INTO TB_ITEM_PEDIDO (QUANTIDADE, ID_PRODUTO, ID_PEDIDO, VALOR_ATUAL_PRODUTO) VALUES (2, 1, 1, 2.40);
INSERT INTO TB_ITEM_PEDIDO (QUANTIDADE, ID_PRODUTO, ID_PEDIDO, VALOR_ATUAL_PRODUTO) VALUES (3, 2, 1, 5.40);

INSERT INTO TB_ITEM_PEDIDO (QUANTIDADE, ID_PRODUTO, ID_PEDIDO, VALOR_ATUAL_PRODUTO) VALUES (2, 1, 2, 2.40);

INSERT INTO TB_ITEM_PEDIDO (QUANTIDADE, ID_PRODUTO, ID_PEDIDO, VALOR_ATUAL_PRODUTO) VALUES (2, 1, 3, 2.40);

INSERT INTO TB_PRODUTO (NOME, PRECO, DATA_INCLUSAO) VALUES ('Produto independente', 5.00, NOW());