server:
  port: 8082

spring:
  application:
    name: api-notificacao
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_REMETENTE}
    password: ${SENHA_REMETENTE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: gabriel
    password: gabriel

broker:
  exchange:
    pedido:
      notificacao:
        event: ms.produto.notificacaoevent
  key:
    pedido:
      notificacao:
        event: ms.produto.notificacaoevent.key
  queue:
    pedido:
      notificacao:
        event: ms.produto.notificacaoevent.queue

logging:
  level:
    br.com.gabrielferreira.notificacao: TRACE

eureka:
  client:
    service-url:
      default-zone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost