create table TB_PRODUTO(
   ID bigserial primary key,
   NOME varchar(255) not null,
   PRECO decimal(10, 2) not null,
   DATA_INCLUSAO TIMESTAMP not null,
   DATA_ATUALIZACAO TIMESTAMP
);

ALTER TABLE TB_PRODUTO add constraint CK_PRODUTO_NOME unique(NOME);
ALTER TABLE TB_PRODUTO ALTER COLUMN DATA_INCLUSAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_PRODUTO ALTER COLUMN DATA_ATUALIZACAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';