INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Administrador', 'ROLE_ADMIN');
INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Funcionário', 'ROLE_FUNCIONARIO');
INSERT INTO TB_PERFIL (DESCRICAO, AUTORIEDADE) VALUES ('Cliente', 'ROLE_CLIENTE');