create table TB_USUARIO(
   ID bigserial primary key,
   NOME varchar(255) not null,
   EMAIL varchar(255) not null,
   SENHA varchar(255) not null,
   DATA_INCLUSAO TIMESTAMP not null,
   DATA_ATUALIZACAO TIMESTAMP
);

ALTER TABLE TB_USUARIO ADD CONSTRAINT CK_USUARIO_EMAIL UNIQUE(EMAIL);
ALTER TABLE TB_USUARIO ALTER COLUMN DATA_INCLUSAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_USUARIO ALTER COLUMN DATA_ATUALIZACAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';