create table TB_USUARIO_PERFIL(
   ID_USUARIO bigserial not null,
   ID_PERFIL bigserial not null
);

ALTER TABLE TB_USUARIO_PERFIL ADD FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID);
ALTER TABLE TB_USUARIO_PERFIL ADD FOREIGN KEY (ID_PERFIL) REFERENCES TB_PERFIL(ID);