create table TB_PEDIDO(
   ID bigserial primary key,
   DATA TIMESTAMP not null,
   DATA_FINALIZADO TIMESTAMP,
   DATA_CANCELADO TIMESTAMP,
   PEDIDO_STATUS varchar(255) not null,
   ID_USUARIO bigserial not null,
   DATA_INCLUSAO TIMESTAMP not null,
   DATA_ATUALIZACAO TIMESTAMP
);

ALTER TABLE TB_PEDIDO ALTER COLUMN DATA SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_PEDIDO ALTER COLUMN DATA_FINALIZADO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_PEDIDO ALTER COLUMN DATA_INCLUSAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_PEDIDO ALTER COLUMN DATA_ATUALIZACAO SET DEFAULT current_timestamp AT TIME ZONE 'UTC';
ALTER TABLE TB_PEDIDO ADD CONSTRAINT CK_PEDIDO_01 check (PEDIDO_STATUS = 'ABERTO' or PEDIDO_STATUS = 'FINALIZADO' or PEDIDO_STATUS = 'CANCELADO');
ALTER TABLE TB_PEDIDO ADD FOREIGN KEY (ID_USUARIO) references TB_USUARIO(ID);